### ISSUE TITLE
Questions about 8. Benchmark Baselines in the paper

### ISSUE THREAD

**Issue by DonghwanKIM0101** [yifeiyin04/Hi4D#6]
Thank you for the great work and dataset deployment!!

I have some questions about the paper.

### SMPL Initialization

In section 6.2 of the supplementary material, use MVPose to output SMPL, and convert it to SMPL-X for DMC input.
For ICON, which model do you use for SMPL or SMPL-X initialization? Ground-truth SMPL or estimated one with (PARE, ROMP, or BEV)?

### Training Dataset

In [GitHub issue](https://github.com/yifeiyin04/Hi4D/issues/4), you did not train or fine-tune SOTA models with Hi4D. Then did you use pre-trained PIFuHD, ICON, and DMC for evaluation?
Pre-trained PIFuHD is trained with RenderP, pre-trained ICON is trained with AGORA, and pre-trained DMC is trained with MultiHuman dataset, right?

**Comment by MoyGcc** [comment]
Hi, thank you for your interest. 

For ICON, We didn't use GT SMPL but just used the built-in code in the repo to infer SMPL initialization. Since DMC uses unpublic code to initialize SMPL-X, we used MVPose to serve as an alternative to do the job. 

Yes, we didn't fine-tune any model on Hi4D but just used pre-trained models for evaluation. I quickly went through their training protocol. I think ICON is trained on multiple datasets (AGORA, THuman, and CAPE) and DMC is trained on a manually simulated dataset which is constructed using Twindom and THuman2.0. If I understand correctly, the MultiHuman dataset is only served for comparisons. Please correct me if I'm wrong.

**Comment by DonghwanKIM0101** [comment]
Thank you for answer!
